services:
  mongo:
    image: percona/percona-server-mongodb:6.0
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/redis:/data
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      RUNNING_IN_DOCKER: "true"
    depends_on:
      - mongo
      - redis
    ports:
      - "4000:4000"

volumes:
  mongo_data:
